// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMXG3m6UbJe8PH2NQtuVhISYX4CCmNHs',
    appId: '1:780550453228:web:decafd2cb0566be71bb2c9',
    messagingSenderId: '780550453228',
    projectId: 'laza-86994',
    authDomain: 'laza-86994.firebaseapp.com',
    storageBucket: 'laza-86994.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4U5NAf5nc4BYQ1RSGD3W8LILzfdEhBE',
    appId: '1:780550453228:android:1b25a0bb318327121bb2c9',
    messagingSenderId: '780550453228',
    projectId: 'laza-86994',
    storageBucket: 'laza-86994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCe4dBRmILT99JBuhvSYwYpmyAkd8E8ck',
    appId: '1:780550453228:ios:d3aae5c94e292b731bb2c9',
    messagingSenderId: '780550453228',
    projectId: 'laza-86994',
    storageBucket: 'laza-86994.appspot.com',
    androidClientId: '780550453228-ohs9v52ja64e3gki0na41vlva60k85ki.apps.googleusercontent.com',
    iosClientId: '780550453228-q4lcb6aga6sb48gdevgiovhvrn6i939o.apps.googleusercontent.com',
    iosBundleId: 'com.example.laza',
  );

}